[package]
name = "rust-optimization-example"
version = "0.1.0"
authors = ["Luca Barbato <lu_zero@gentoo.org>"]

[lib]
name = "lib"
path = "src/testcases.rs"

[[bin]]
name = "tester"
path = "src/main.rs"

[dependencies]
itertools = "0.6.*"
time = "0.1.*"
